config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  devise_for :users
  root "static_pages#index"  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :beers
  resources :comments

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
  acts_as_commentable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  role                   :integer
#

class User < ApplicationRecord

  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  def respond_modal_with(*args, &blk)
    options = args.extract_options!
    options[:responder] = ModalResponder
    respond_with *args, options, &blk
  end

  end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
    @new_comment    = Comment.build_from(@beer, current_user.id, "")
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: 'Beer was successfully created.' }
        format.json { render :show, status: :created, location: @beer }
      else
        format.html { render :new }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url, notice: 'Beer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:name, :description)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    commentable = commentable_type.constantize.find(commentable_id)
    @comment = Comment.build_from(commentable, current_user.id, body)

    respond_to do |format|
      if @comment.save
        make_child_comment
        format.html  { redirect_to(:back, :notice => 'Comment was successfully added.') }
      else
        format.html  { render :action => "new" }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type, :comment_id)
  end

  def commentable_type
    comment_params[:commentable_type]
  end

  def commentable_id
    comment_params[:commentable_id]
  end

  def comment_id
    comment_params[:comment_id]
  end

  def body
    comment_params[:body]
  end

  def make_child_comment
    return "" if comment_id.blank?

    parent_comment = Comment.find comment_id
    @comment.move_to_child_of(parent_comment)
  end

end

app/controllers/hello_world_controller.rb
class HelloWorldController < ApplicationController
  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_flash_class(flash_type)
    { success: 'alert-success',
      error:   'alert-danger',
      alert:   'alert-warning',
      notice:  'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.slim
= simple_form_for(@beer) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description

  .form-actions
    = f.button :submit

app/views/beers/edit.html.slim
.page-header
  = link_to beers_path, class: 'btn btn-default' do
    i.fa.fa-list-alt
    |  Back 
  = link_to @beer, class: 'btn btn-primary' do
    i.fa.fa-info-circle
    |  Show 
  h1
    | Editing 
    | beer

= render 'form'

app/views/beers/index.html.slim
.page-header
  = link_to new_beer_path, class: 'btn btn-primary' do 
    i.fa.fa-plus
    |  New Beer
  h1
    | Listing beers

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Name
        th
          | Description
        th
        th
        th
    tbody
      - @beers.each do | beer |
        tr
          td
            = beer.name
          td
            = beer.description
          td
            = link_to 'Show', beer
          td
            = link_to 'Edit', edit_beer_path(beer) 
          td
            = link_to 'Destroy', beer, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/beers/new.html.slim
.page-header
  = link_to beers_path, class: 'btn btn-default' do 
    i.fa.fa-list-alt
    |  Back 
  h1
    | New 
    | beer

= render 'form'

app/views/beers/show.html.slim
.page-header
  = link_to beers_path, class: 'btn btn-default' do 
    i.fa.fa-list-alt
    |  Back 
  = link_to edit_beer_path(@beer), class: 'btn btn-primary' do 
    i.fa.fa-pencil
    |  Edit 
  h1
    | Show beer
dl.dl-horizontal
  dt
    | Name:
  dd
    = @beer.name
  dt
    | Description:
  dd
    = @beer.description


= render partial: "comments/template", locals: {commentable: @beer, new_comment: @comment}

app/views/comments/_form.html.erb
<%= form_for @new_comment do |f| %>
  <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
  <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
  <div class="field form-group">
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= submit_tag "Post comment", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/comments/_reply.html.erb
<% comments.each do |comment| %>
  <div class="comments-show">
    <div class="comment">
      <p><%= comment.body %><br></p>
      <div class="comment-nav"><a href="#" class="comment-reply">reply</a></div>
      <div class="reply-form">
        <%= form_for @new_comment do |f| %>
          <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
          <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
          <%= f.hidden_field :comment_id, value: comment.id %>
          <div class="field form-group">
            <%= f.text_area :body, class: 'form-control' %>
          </div>
          <div class="field form-group">
            <%= submit_tag "Post Reply", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
    <%= render partial: "comments/reply", locals: {comments: comment.children} %>
  </div>
<% end %>

app/views/comments/_template.html.erb
<div class="comments-header">
  <h4>
    <%= commentable.comment_threads.count == 0 ? "no" : commentable.comment_threads.count %> comments
  </h4>
</div>

<%= render partial: "comments/form", locals: {new_comment: new_comment} %>

<div class="comments-container">  
  <%= render partial: "comments/reply", locals: {comments: commentable.root_comments} %>
</div>

app/views/hello_world/index.html.erb
<h1 class="alert alert-info this-works">Hello World</h1>
<%= react_component("HelloWorldApp", props: @hello_world_props, prerender: false) %>

app/views/layouts/application.slim
doctype html
html
  head
    title BoosterShot
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    nav.navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button" 
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"  BoosterShot
        #navbar.collapse.navbar-collapse
          ul.nav.navbar-nav
            li.active
              a href="#"  Home
            li
              a href="#about"  About
            li
              a href="#contact"  Contact
            li.dropdown
              a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" 
                | Dropdown
                span.caret
              ul.dropdown-menu
                li
                  a href="#"  Action
                li
                  a href="#"  Another action
                li
                  a href="#"  Something else here
                li.divider role="separator" 
                li.dropdown-header Nav header
                li
                  a href="#"  Separated link
                li
                  a href="#"  One more separated link
          ul.nav.navbar-nav.nav-pills.pull-right
            - if user_signed_in?
              li = link_to('Edit Account', edit_user_registration_path)
              li = link_to "Sign out", destroy_user_session_path, :method => :delete
            - else
              li = link_to "Sign in", new_user_session_path
              li = link_to "Sign up", new_user_registration_path
        /! /.nav-collapse
    /! Begin page content
    .container
      = render 'shared/flash'
      = yield
    #modal-holder
    footer.footer
      .container
        p.text-muted 2016 &copy; BoosterShot

app/views/layouts/modal.html.slim
#mainModal.modal tabindex="-1" role="dialog" aria-labelledby="mainModalLabel" aria-hidden="true"
  .modal-dialog
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal"
          span aria-hidden="true"
            | &times;
          span.sr-only
            | Close
        h4#mainModalLabel.modal-title
          = yield :title if content_for? :title
          | &nbsp;
      = yield

app/views/shared/_flash.slim
- flash.each do |type, message|
  .alert.fade.in class=(bootstrap_flash_class(type))
    = message
    button.close[type="button" data-dismiss="alert" aria-label="Close"]
      span[aria-hidden="true"]
        | ×

app/views/static_pages/index.slim
.bshot
  i.fa.fa-eye.fa-5x
  i.fa.fa-heart.fa-5x
  i.fa.fa-beer.fa-5x